version: '3.1'

services:
  database:
    container_name: mysql-blog-api
    platform: linux/x86_64
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - 3306:3306
    networks:
      - spring-boot
  database-client:
    container_name: adminer-blog-api
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_DB_DRIVER: mysql
      ADMINER_DEFAULT_DB_HOST: database
      ADMINER_DESIGN: haeckel
      ADMINER_PLUGINS: tables-filter tinymce
    ports:
      - 54320:8080
    networks:
      - spring-boot
  mailhog:
    container_name: mailer-blog-api
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - spring-boot
networks:
  spring-boot:
    driver: bridge
